CREATE TABLE IF NOT EXISTS events (
 id TEXT PRIMARY KEY, slug TEXT NOT NULL UNIQUE, status TEXT NOT NULL,
 starts_at TEXT NOT NULL, ends_at TEXT NOT NULL, updated_at TEXT NOT NULL,
 revision INTEGER NOT NULL DEFAULT 1, data TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS event_schedule ON events(status,starts_at);
CREATE TABLE IF NOT EXISTS proposals (
 id TEXT PRIMARY KEY, state TEXT NOT NULL DEFAULT 'pending', created_at TEXT NOT NULL, data TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS login_tokens (hash TEXT PRIMARY KEY, email TEXT NOT NULL, expires_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS sessions (hash TEXT PRIMARY KEY, email TEXT NOT NULL, csrf TEXT NOT NULL, expires_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS limits (key TEXT PRIMARY KEY, count INTEGER NOT NULL, expires_at INTEGER NOT NULL);
