export const copy = {
  en: {
    programme: "Programme",
    archive: "Archive",
    visit: "Visit us",
    propose: "Propose an event",
    admin: "Admin",
    skip: "Skip to content",
    edition: "INDEPENDENT CINEMA · ALBUQUERQUE, NM",
    tagline: "A small room. A big screen.\nA different kind of night out.",
    intro:
      "Films, conversations, and things worth gathering for. A 30-seat microcinema inside the Dust Wave studio.",
    upcoming: "Coming to the Microcinema",
    eyebrow: "THE PROGRAMME",
    next: "NEXT AT DUST WAVE",
    more: "View event",
    tickets: "Buy tickets",
    rsvp: "RSVP",
    calendar: "Add to calendar",
    walkin: "No RSVP needed",
    cancelled: "Cancelled",
    past: "Past event",
    back: "Back to programme",
    free: "Free entry",
    when: "WHEN",
    where: "WHERE",
    admission: "ADMISSION",
    empty: "The next programme is taking shape.",
    emptyBody:
      "New screenings and events will appear here. In the meantime, get to know the space or tell us what you’d like to put on.",
    archiveEmpty: "The archive starts with our first event.",
    archiveIntro:
      "A record of the films, conversations, and gatherings that have passed through our little room.",
    visitTitle: "Come on in.",
    visitIntro:
      "An intimate, welcoming space for screenings, artist talks, and community gatherings.",
    room: "THE ROOM",
    roomBody:
      "Our 700 sq. ft., 30-seat screening room is inside the Dust Wave studio. Popcorn, snacks, candy, drinks, and Dust Wave merch are available at screenings and events. A donation box helps support the space.",
    parking: "A NOTE ON PARKING",
    parkingBody:
      "Please do not park directly in front of the studio on Haines Avenue. That curb needs to stay clear for warehouse trucks. Park across the street, or on 7th or 8th Street. Give yourself a few extra minutes to walk over.",
    directions: "Get directions",
    access: "For access questions or venue rental, email",
    proposeTitle: "Have something in mind?",
    proposeBody:
      "A film, a conversation, an experiment. Tell us what you’d like to bring to the Microcinema. Every proposal is reviewed; submitting this form does not confirm a booking.",
    private:
      "Your name and email are private. We use them only to review and respond to your proposal.",
    name: "Your name",
    email: "Email address",
    title: "Event title",
    description: "Description",
    date: "Date",
    time: "Start time",
    endTime: "End time",
    endDate: "End date",
    send: "Send proposal",
    sent: "Proposal received. We’ll review your idea and get in touch by email.",
    signin: "Sign in to the Microcinema",
    signinBody: "We’ll email a one-time sign-in link to your admin address.",
    sendLink: "Send sign-in link",
    linkSent:
      "If this address has access, a sign-in link is on its way. It expires in 15 minutes.",
    localLink: "Open local test sign-in",
    localNote:
      "Local preview · sample programme. These are not announced events.",
    events: "Events",
    proposals: "Proposals",
    add: "Add event",
    edit: "Edit",
    remove: "Remove",
    save: "Save event",
    close: "Close",
    logout: "Sign out",
    newEvent: "New event",
    editEvent: "Edit event",
    slug: "Page address",
    slugHelp:
      "Use lowercase words with hyphens. The address stays fixed after the first save.",
    details: "Film / programme details",
    detailsHelp: "Director, year, running time, language, subtitles, guests…",
    price: "Admission label",
    priceHelp: "For example: $10 general admission or Free entry",
    mode: "Event button",
    status: "Publication",
    draft: "Draft",
    published: "Published",
    link: "Ticket / RSVP URL",
    artwork: "Artwork",
    artworkHelp:
      "JPEG, PNG, or WebP, up to 5 MB. Images are resized before upload.",
    alt: "Image description",
    preview: "View public page",
    saved: "Event saved.",
    confirmDelete:
      "Remove this event? It will disappear from the website. You can restore it from the removed list.",
    restore: "Restore",
    removed: "Removed events",
    noEvents: "No events yet. Add your first screening or gathering.",
    noProposals: "No pending proposals.",
    makeDraft: "Create draft",
    dismiss: "Dismiss",
    pending: "Pending review",
    proposalDismiss: "Dismiss this proposal?",
    english: "English",
    spanish: "Spanish",
    optional: "Optional",
    spanishHelp:
      "Spanish text is optional; English appears when a translation is empty.",
    timezone: "All dates and times are Albuquerque time (America/Denver).",
    requiredHint: "Fields marked * are required.",
    discard: "Discard unsaved changes?",
    genericError:
      "Something went wrong. Your entries are still here; please try again.",
    unauthorized:
      "Your session has expired. Save your text before signing in again.",
    invalid_login:
      "That sign-in link is invalid or expired. Request a new one.",
    invalid_date:
      "Enter a valid date and time. Times skipped by daylight saving are not valid.",
    ambiguous_time:
      "This time occurs twice when daylight saving ends. Choose a time outside the repeated hour.",
    invalid_end_time: "The end must be after the start, and within seven days.",
    invalid_url: "Enter a complete HTTPS link.",
    shop_url_required: "Ticket links must point to shop.dustwave.xyz.",
    required: "Please complete all required fields.",
    invalid_slug:
      "Use lowercase letters, numbers, and single hyphens for the page address.",
    slug_locked: "An existing page address cannot be changed.",
    slug_taken: "That page address is already in use.",
    conflict:
      "This event changed in another session. Your draft is preserved. Close and reopen it to load the saved version.",
    rate_limited: "Too many attempts. Please try again in 15 minutes.",
    challenge_required: "Complete the verification before sending.",
    challenge_not_configured:
      "This form is not ready yet. Please email info@dustwave.xyz.",
    challenge_failed: "Verification failed. Please try again.",
    challenge_unavailable:
      "Verification is temporarily unavailable. Please try again.",
    login_unavailable: "We couldn’t send your sign-in link. Please try again.",
    file_too_large: "Choose an image smaller than 5 MB.",
    invalid_image: "Choose a JPEG, PNG, or WebP image.",
    notFound: "This page isn’t here.",
    notFoundBody:
      "The event may have been removed, or the address may be incorrect.",
    notice: "Audience notes",
    footer: "A space for independent cinema & shared experience.",
    readMore: "Read more",
    removeImage: "Remove artwork",
    uploading: "Preparing artwork…",
    privacy: "Proposal privacy",
    privacyText:
      "Proposal contact details are visible only to Microcinema administrators. They are used to review your idea and contact you about it. To ask for deletion, email info@dustwave.xyz. No mailing-list subscription is created.",
    emptyArtwork: "EVENT ARTWORK",
    sessionLoad: "Checking your session…",
  },
  es: {
    programme: "Programa",
    archive: "Archivo",
    visit: "Visítanos",
    propose: "Propón un evento",
    admin: "Administración",
    skip: "Ir al contenido",
    edition: "CINE INDEPENDIENTE · ALBUQUERQUE, NM",
    tagline: "Una sala pequeña. Una gran pantalla.\nUna noche diferente.",
    intro:
      "Películas, conversaciones y motivos para reunirnos. Un microcine de 30 butacas dentro del estudio Dust Wave.",
    upcoming: "Próximamente en el Microcine",
    eyebrow: "EL PROGRAMA",
    next: "LO PRÓXIMO EN DUST WAVE",
    more: "Ver evento",
    tickets: "Comprar entradas",
    rsvp: "Reservar",
    calendar: "Añadir al calendario",
    walkin: "Sin reserva",
    cancelled: "Cancelado",
    past: "Evento pasado",
    back: "Volver al programa",
    free: "Entrada gratuita",
    when: "CUÁNDO",
    where: "DÓNDE",
    admission: "ENTRADA",
    empty: "Estamos preparando el próximo programa.",
    emptyBody:
      "Las nuevas proyecciones y actividades aparecerán aquí. Mientras tanto, conoce el espacio o cuéntanos qué te gustaría organizar.",
    archiveEmpty: "El archivo comienza con nuestro primer evento.",
    archiveIntro:
      "Un registro de las películas, conversaciones y encuentros que han pasado por nuestra pequeña sala.",
    visitTitle: "Pasa, estás en casa.",
    visitIntro:
      "Un espacio íntimo y acogedor para proyecciones, charlas con artistas y encuentros comunitarios.",
    room: "LA SALA",
    roomBody:
      "Nuestra sala de 700 pies cuadrados y 30 butacas está dentro del estudio Dust Wave. Hay palomitas, aperitivos, dulces, bebidas y productos de Dust Wave a la venta. Una caja de donaciones ayuda a sostener el espacio.",
    parking: "SOBRE EL ESTACIONAMIENTO",
    parkingBody:
      "No estaciones justo frente al estudio en Haines Avenue. Ese tramo debe quedar libre para los camiones del almacén. Puedes estacionar al otro lado de la calle, o en las calles 7 y 8. Llega con unos minutos de margen para caminar hasta la sala.",
    directions: "Cómo llegar",
    access: "Para consultas de accesibilidad o alquiler, escribe a",
    proposeTitle: "¿Tienes algo en mente?",
    proposeBody:
      "Una película, una conversación, un experimento. Cuéntanos qué te gustaría traer al Microcine. Revisamos cada propuesta; este formulario no confirma una reserva.",
    private:
      "Tu nombre y correo son privados. Solo los usamos para revisar y responder a tu propuesta.",
    name: "Tu nombre",
    email: "Correo electrónico",
    title: "Título del evento",
    description: "Descripción",
    date: "Fecha",
    time: "Hora de inicio",
    endTime: "Hora de fin",
    endDate: "Fecha de fin",
    send: "Enviar propuesta",
    sent: "Propuesta recibida. Revisaremos tu idea y nos pondremos en contacto por correo.",
    signin: "Accede al Microcine",
    signinBody:
      "Enviaremos un enlace de un solo uso a tu correo de administración.",
    sendLink: "Enviar enlace de acceso",
    linkSent:
      "Si esta dirección tiene acceso, recibirá un enlace que caduca en 15 minutos.",
    localLink: "Abrir acceso de prueba local",
    localNote:
      "Vista previa local · programa de ejemplo. Estos eventos no están anunciados.",
    events: "Eventos",
    proposals: "Propuestas",
    add: "Añadir evento",
    edit: "Editar",
    remove: "Quitar",
    save: "Guardar evento",
    close: "Cerrar",
    logout: "Cerrar sesión",
    newEvent: "Nuevo evento",
    editEvent: "Editar evento",
    slug: "Dirección de la página",
    slugHelp:
      "Usa palabras en minúsculas separadas por guiones. La dirección queda fija al guardar por primera vez.",
    details: "Detalles de la película / programa",
    detailsHelp: "Dirección, año, duración, idioma, subtítulos, invitados…",
    price: "Texto de la entrada",
    priceHelp: "Por ejemplo: Entrada general $10 o Entrada gratuita",
    mode: "Botón del evento",
    status: "Publicación",
    draft: "Borrador",
    published: "Publicado",
    link: "URL de entradas / reservas",
    artwork: "Imagen",
    artworkHelp:
      "JPEG, PNG o WebP, hasta 5 MB. Se reduce el tamaño antes de subirla.",
    alt: "Descripción de la imagen",
    preview: "Ver página pública",
    saved: "Evento guardado.",
    confirmDelete:
      "¿Quitar este evento del sitio? Puedes recuperarlo desde la lista de eventos quitados.",
    restore: "Recuperar",
    removed: "Eventos quitados",
    noEvents: "Aún no hay eventos. Añade tu primera proyección o actividad.",
    noProposals: "No hay propuestas pendientes.",
    makeDraft: "Crear borrador",
    dismiss: "Descartar",
    pending: "Pendiente de revisión",
    proposalDismiss: "¿Descartar esta propuesta?",
    english: "Inglés",
    spanish: "Español",
    optional: "Opcional",
    spanishHelp:
      "El texto en español es opcional; se muestra el inglés cuando falta una traducción.",
    timezone:
      "Todas las fechas y horas corresponden a Albuquerque (America/Denver).",
    requiredHint: "Los campos con * son obligatorios.",
    discard: "¿Descartar los cambios sin guardar?",
    genericError:
      "Ocurrió un error. Tus datos siguen aquí; inténtalo de nuevo.",
    unauthorized:
      "Tu sesión ha caducado. Guarda tu texto antes de volver a acceder.",
    invalid_login: "El enlace no es válido o ha caducado. Solicita uno nuevo.",
    invalid_date:
      "Introduce una fecha y hora válidas. Las horas omitidas por el cambio de horario no son válidas.",
    ambiguous_time:
      "Esta hora se repite al terminar el horario de verano. Elige una hora fuera de ese intervalo.",
    invalid_end_time:
      "El fin debe ser posterior al inicio y dentro de siete días.",
    invalid_url: "Introduce un enlace HTTPS completo.",
    shop_url_required: "Las entradas deben enlazar a shop.dustwave.xyz.",
    required: "Completa todos los campos obligatorios.",
    invalid_slug: "Usa minúsculas, números y guiones para la dirección.",
    slug_locked: "La dirección de una página existente no se puede cambiar.",
    slug_taken: "Esta dirección ya está en uso.",
    conflict:
      "Otra sesión modificó este evento. Tu borrador se conserva. Cierra y vuelve a abrirlo para cargar la versión guardada.",
    rate_limited: "Demasiados intentos. Vuelve a intentarlo en 15 minutos.",
    challenge_required: "Completa la verificación antes de enviar.",
    challenge_not_configured:
      "Este formulario aún no está listo. Escribe a info@dustwave.xyz.",
    challenge_failed: "Falló la verificación. Inténtalo de nuevo.",
    challenge_unavailable:
      "La verificación no está disponible. Inténtalo de nuevo.",
    login_unavailable: "No pudimos enviar el enlace. Inténtalo de nuevo.",
    file_too_large: "Elige una imagen de menos de 5 MB.",
    invalid_image: "Elige una imagen JPEG, PNG o WebP.",
    notFound: "Esta página no está aquí.",
    notFoundBody:
      "El evento puede haberse quitado o la dirección puede ser incorrecta.",
    notice: "Avisos al público",
    footer:
      "Un espacio para el cine independiente y la experiencia compartida.",
    readMore: "Leer más",
    removeImage: "Quitar imagen",
    uploading: "Preparando imagen…",
    privacy: "Privacidad de las propuestas",
    privacyText:
      "Solo la administración del Microcine puede ver los datos de contacto de las propuestas. Los usamos para revisar tu idea y contactarte. Para solicitar su eliminación, escribe a info@dustwave.xyz. No te suscribimos a una lista de correo.",
    emptyArtwork: "IMAGEN DEL EVENTO",
    sessionLoad: "Comprobando tu sesión…",
  },
};
