export const copy = {
  en: {
    moreInfo: "More information",
    infoUrl: "More information URL (optional)",
    infoLabel: "Link text (optional)",
    repeat: "Repeat",
    noRepeat: "Does not repeat",
    weekly: "Every week",
    fortnightly: "Every other week",
    repeatHelp:
      "Each meeting gets its own listing for the next three months. Save the series to manage individual dates.",
    seriesHelp:
      "Changes here apply to the whole series. The first date and repeat pattern stay fixed. To change the pattern, end this series and create another.",
    repeatUntil: "Repeat until",
    repeatUntilHelp:
      "Optional. Include meetings through this date, or leave blank to keep repeating.",
    meetings: "Individual meetings",
    meetingsHelp:
      "Upcoming meetings for the next three months, plus any dates you have changed. Cancel or reschedule a meeting here, then save the event.",
    originalDate: "Originally scheduled for",
    meetingStatus: "Meeting status",
    scheduled: "Scheduled",
    resetMeeting: "Reset to series schedule",
    invalid_repeat: "Choose a supported repeat schedule.",
    series_locked:
      "The first date and repeat pattern stay fixed. End this series and create another to change the pattern.",
    invalid_repeat_end:
      "The repeat end date must be on or after the first meeting, and no later than 2100.",
    invalid_exception:
      "Check the individual meeting dates. Each must belong to the series, with no duplicates (up to 100 changed dates).",
    recurrence_time:
      "Recurring Sunday events cannot start or end from 1–2:59 a.m. because of daylight saving changes.",
    programme: "Events",
    archive: "Archive",
    visit: "Visit us",
    propose: "Propose an event",
    admin: "Admin",
    skip: "Skip to content",
    siteDescription:
      "Film screenings and events at Dust Wave Microcinema in Albuquerque, New Mexico.",
    next: "UP NEXT",
    more: "View event",
    tickets: "Buy tickets",
    rsvp: "RSVP",
    calendar: "Add to calendar",
    walkin: "No RSVP needed",
    cancelled: "Canceled",
    past: "Past event",
    back: "Back to events",
    free: "Free admission",
    when: "WHEN",
    where: "WHERE",
    admission: "ADMISSION",
    empty: "More screenings on the way.",
    emptyBody:
      "We’ll post the next events here. In the meantime, take a look at the space or send us an idea for something you’d like to host.",
    archiveEmpty: "No past events yet.",
    room: "THE ROOM",
    roomLocation: "The Dust Wave Microcinema is located at",
    roomDetails: [
      "Our 700-square-foot screening room seats 30 people.",
      "We sell popcorn, snacks, candy, drinks, and Dust Wave merch at events.",
      "There’s a donation box if you’d like to help keep the space going.",
    ],
    parking: "PARKING",
    parkingDetails: [
      "Please keep the curb in front of the studio clear. Trucks from our neighbors at Northern New Mexico Logistics need to get in and out of the adjacent warehouse.",
      "You can park across Haines Avenue or along 7th or 8th Street.",
      "Give yourself a few extra minutes to park and walk over.",
    ],
    directions: "Get directions",
    access: "For accessibility questions or info about renting the room, email",
    proposeTitle: "Have an idea for an event?",
    proposeBody:
      "Tell us what you’d like to show or organize, and when. We’ll take a look and follow up by email. This form doesn’t reserve the room.",
    private:
      "Only our team sees your name and email. We’ll use them to get back to you about your idea.",
    name: "Your name",
    email: "Email address",
    title: "Event title",
    description: "Description",
    date: "Date",
    time: "Start time",
    endTime: "End time",
    endDate: "End date",
    send: "Send proposal",
    sent: "Got it, thanks! We’ll look over your idea and get back to you by email.",
    signin: "Sign in to the Microcinema",
    signinBody: "We’ll email a one-time sign-in link to your admin address.",
    sendLink: "Send sign-in link",
    linkSent:
      "If this address has access, a sign-in link is on its way. It expires in 15 minutes.",
    localLink: "Open local test sign-in",
    localNote: "Local preview · includes clearly marked sample events.",
    events: "Events",
    proposals: "Proposals",
    add: "Add event",
    edit: "Edit",
    remove: "Remove",
    save: "Save event",
    close: "Close",
    logout: "Sign out",
    newEvent: "New event",
    editEvent: "Edit event",
    slug: "Page address",
    slugHelp:
      "Use lowercase words with hyphens. The address stays fixed after the first save.",
    details: "Film / event details",
    detailsHelp: "Director, year, running time, language, subtitles, guests…",
    price: "Admission label",
    priceHelp: "For example: $10 general admission or Free admission",
    mode: "Event button",
    status: "Publication",
    draft: "Draft",
    published: "Published",
    link: "Ticket / RSVP URL",
    artwork: "Artwork",
    artworkHelp:
      "JPEG, PNG, or WebP, up to 5 MB. Images are resized before upload.",
    alt: "Image description",
    preview: "View public page",
    saved: "Event saved.",
    confirmDelete:
      "Remove this event? It will disappear from the website. You can restore it from the removed list.",
    restore: "Restore",
    removed: "Removed events",
    noEvents: "No events yet. Add your first one.",
    noProposals: "No pending proposals.",
    makeDraft: "Create draft",
    dismiss: "Dismiss",
    pending: "Pending review",
    proposalDismiss: "Dismiss this proposal?",
    english: "English",
    spanish: "Spanish",
    optional: "Optional",
    spanishHelp:
      "Spanish text is optional; English appears when a translation is empty.",
    timezone: "All dates and times are Albuquerque time (America/Denver).",
    requiredHint: "Fields marked * are required.",
    discard: "Discard unsaved changes?",
    genericError:
      "That didn’t go through. Your entries are still here. Please try again.",
    unauthorized:
      "Your session has expired. Save your text before signing in again.",
    invalid_login:
      "That sign-in link is invalid or expired. Request a new one.",
    invalid_date:
      "Enter a valid date and time. Times skipped by daylight saving are not valid.",
    ambiguous_time:
      "This time occurs twice when daylight saving ends. Choose a time outside the repeated hour.",
    invalid_end_time: "The end must be after the start, and within seven days.",
    invalid_url: "Enter a complete HTTPS link.",
    shop_url_required: "Ticket links must point to shop.dustwave.xyz.",
    required: "Please complete all required fields.",
    invalid_slug:
      "Use lowercase letters, numbers, and single hyphens for the page address.",
    slug_locked: "An existing page address cannot be changed.",
    slug_taken: "That page address is already in use.",
    conflict:
      "This event changed in another session. Your draft is preserved. Close and reopen it to load the saved version.",
    rate_limited: "Too many attempts. Please try again in 15 minutes.",
    challenge_required: "Complete the verification before sending.",
    challenge_not_configured:
      "This form is not ready yet. Please email info@dustwave.xyz.",
    challenge_failed: "Verification failed. Please try again.",
    challenge_unavailable:
      "Verification is temporarily unavailable. Please try again.",
    login_unavailable: "We couldn’t send your sign-in link. Please try again.",
    file_too_large: "Choose an image smaller than 5 MB.",
    invalid_image: "Choose a JPEG, PNG, or WebP image.",
    notFound: "We can’t find this page.",
    notFoundBody:
      "The event may have been removed, or the address may be incorrect.",
    notice: "Audience notes",
    readMore: "Read more",
    removeImage: "Remove artwork",
    uploading: "Preparing artwork…",
    privacy: "Privacy",
    privacyText:
      "Only the Microcinema team can see the contact details you send with a proposal. We use them to review your idea and get back to you. We don’t add you to a mailing list. To have your proposal deleted, email info@dustwave.xyz.",
    emptyArtwork: "EVENT ARTWORK",
    sessionLoad: "Checking your session…",
    venueNote: "30 SEATS\nDUST WAVE STUDIO",
  },
  es: {
    moreInfo: "Más información",
    infoUrl: "URL con más información (opcional)",
    infoLabel: "Texto del enlace (opcional)",
    repeat: "Repetir",
    noRepeat: "No se repite",
    weekly: "Cada semana",
    fortnightly: "Cada dos semanas",
    repeatHelp:
      "Cada reunión tiene su propio anuncio para los próximos tres meses. Guarda la serie para modificar fechas individuales.",
    seriesHelp:
      "Estos cambios afectan a toda la serie. La primera fecha y el patrón quedan fijos. Para cambiar el patrón, termina esta serie y crea otra.",
    repeatUntil: "Repetir hasta",
    repeatUntilHelp:
      "Opcional. Incluye reuniones hasta esta fecha. Déjalo vacío para seguir repitiendo.",
    meetings: "Reuniones individuales",
    meetingsHelp:
      "Reuniones de los próximos tres meses y fechas que has modificado. Cancela o cambia una reunión aquí y después guarda el evento.",
    originalDate: "Fecha original",
    meetingStatus: "Estado de la reunión",
    scheduled: "Programada",
    resetMeeting: "Restablecer la fecha de la serie",
    invalid_repeat: "Elige una opción de repetición válida.",
    series_locked:
      "La primera fecha y el patrón quedan fijos. Termina esta serie y crea otra para cambiar el patrón.",
    invalid_repeat_end:
      "La fecha final debe ser igual o posterior a la primera reunión y no superar el año 2100.",
    invalid_exception:
      "Revisa las fechas individuales. Deben pertenecer a la serie, sin duplicados (hasta 100 fechas modificadas).",
    recurrence_time:
      "Las reuniones recurrentes del domingo no pueden comenzar ni terminar entre la 1 y las 2:59 a. m. por los cambios de horario.",
    programme: "Eventos",
    archive: "Archivo",
    visit: "Visítanos",
    propose: "Propón un evento",
    admin: "Administración",
    skip: "Ir al contenido",
    siteDescription:
      "Proyecciones y eventos en el Microcine Dust Wave en Albuquerque, Nuevo México.",
    next: "PRÓXIMAMENTE",
    more: "Ver evento",
    tickets: "Comprar entradas",
    rsvp: "Reservar",
    calendar: "Añadir al calendario",
    walkin: "Sin reserva",
    cancelled: "Cancelado",
    past: "Evento pasado",
    back: "Volver a los eventos",
    free: "Entrada gratuita",
    when: "CUÁNDO",
    where: "DÓNDE",
    admission: "ENTRADA",
    empty: "Pronto habrá más funciones.",
    emptyBody:
      "Publicaremos los próximos eventos aquí. Mientras tanto, conoce el espacio o mándanos una idea de lo que te gustaría organizar.",
    archiveEmpty: "Todavía no hay eventos anteriores.",
    room: "LA SALA",
    roomLocation: "El Microcine Dust Wave está ubicado en",
    roomDetails: [
      "Nuestra sala ocupa 700 pies cuadrados y tiene 30 butacas.",
      "En los eventos vendemos palomitas, snacks, dulces, bebidas y productos de Dust Wave.",
      "Hay una caja de donaciones si quieres ayudarnos a mantener el espacio.",
    ],
    parking: "ESTACIONAMIENTO",
    parkingDetails: [
      "Por favor, deja libre el frente del estudio. Los camiones de nuestros vecinos de Northern New Mexico Logistics necesitan entrar y salir del almacén contiguo.",
      "Puedes estacionar al otro lado de Haines Avenue o en las calles 7 y 8.",
      "Ven con unos minutos de margen para estacionar y caminar hasta la sala.",
    ],
    directions: "Cómo llegar",
    access:
      "Si tienes preguntas sobre accesibilidad o quieres alquilar la sala, escribe a",
    proposeTitle: "¿Tienes una idea para un evento?",
    proposeBody:
      "Cuéntanos qué quieres mostrar u organizar y cuándo. Revisaremos tu propuesta y te responderemos por correo. Este formulario no reserva la sala.",
    private:
      "Solo nuestro equipo puede ver tu nombre y correo. Los usaremos para responderte sobre tu idea.",
    name: "Tu nombre",
    email: "Correo electrónico",
    title: "Título del evento",
    description: "Descripción",
    date: "Fecha",
    time: "Hora de inicio",
    endTime: "Hora de fin",
    endDate: "Fecha de fin",
    send: "Enviar propuesta",
    sent: "¡Gracias! Revisaremos tu idea y te responderemos por correo.",
    signin: "Accede al Microcine",
    signinBody:
      "Enviaremos un enlace de un solo uso a tu correo de administración.",
    sendLink: "Enviar enlace de acceso",
    linkSent:
      "Si esta dirección tiene acceso, recibirá un enlace que caduca en 15 minutos.",
    localLink: "Abrir acceso de prueba local",
    localNote:
      "Vista previa local · incluye eventos de ejemplo identificados como tales.",
    events: "Eventos",
    proposals: "Propuestas",
    add: "Añadir evento",
    edit: "Editar",
    remove: "Quitar",
    save: "Guardar evento",
    close: "Cerrar",
    logout: "Cerrar sesión",
    newEvent: "Nuevo evento",
    editEvent: "Editar evento",
    slug: "Dirección de la página",
    slugHelp:
      "Usa palabras en minúsculas separadas por guiones. La dirección queda fija al guardar por primera vez.",
    details: "Detalles de la película / evento",
    detailsHelp: "Dirección, año, duración, idioma, subtítulos, invitados…",
    price: "Texto de la entrada",
    priceHelp: "Por ejemplo: Entrada general $10 o Entrada gratuita",
    mode: "Botón del evento",
    status: "Publicación",
    draft: "Borrador",
    published: "Publicado",
    link: "URL de entradas / reservas",
    artwork: "Imagen",
    artworkHelp:
      "JPEG, PNG o WebP, hasta 5 MB. Se reduce el tamaño antes de subirla.",
    alt: "Descripción de la imagen",
    preview: "Ver página pública",
    saved: "Evento guardado.",
    confirmDelete:
      "¿Quitar este evento del sitio? Puedes recuperarlo desde la lista de eventos quitados.",
    restore: "Recuperar",
    removed: "Eventos quitados",
    noEvents: "Aún no hay eventos. Añade tu primera proyección o actividad.",
    noProposals: "No hay propuestas pendientes.",
    makeDraft: "Crear borrador",
    dismiss: "Descartar",
    pending: "Pendiente de revisión",
    proposalDismiss: "¿Descartar esta propuesta?",
    english: "Inglés",
    spanish: "Español",
    optional: "Opcional",
    spanishHelp:
      "El texto en español es opcional; se muestra el inglés cuando falta una traducción.",
    timezone:
      "Todas las fechas y horas corresponden a Albuquerque (America/Denver).",
    requiredHint: "Los campos con * son obligatorios.",
    discard: "¿Descartar los cambios sin guardar?",
    genericError:
      "Ocurrió un error. Tus datos siguen aquí; inténtalo de nuevo.",
    unauthorized:
      "Tu sesión ha caducado. Guarda tu texto antes de volver a acceder.",
    invalid_login: "El enlace no es válido o ha caducado. Solicita uno nuevo.",
    invalid_date:
      "Introduce una fecha y hora válidas. Las horas omitidas por el cambio de horario no son válidas.",
    ambiguous_time:
      "Esta hora se repite al terminar el horario de verano. Elige una hora fuera de ese intervalo.",
    invalid_end_time:
      "El fin debe ser posterior al inicio y dentro de siete días.",
    invalid_url: "Introduce un enlace HTTPS completo.",
    shop_url_required: "Las entradas deben enlazar a shop.dustwave.xyz.",
    required: "Completa todos los campos obligatorios.",
    invalid_slug: "Usa minúsculas, números y guiones para la dirección.",
    slug_locked: "La dirección de una página existente no se puede cambiar.",
    slug_taken: "Esta dirección ya está en uso.",
    conflict:
      "Otra sesión modificó este evento. Tu borrador se conserva. Cierra y vuelve a abrirlo para cargar la versión guardada.",
    rate_limited: "Demasiados intentos. Vuelve a intentarlo en 15 minutos.",
    challenge_required: "Completa la verificación antes de enviar.",
    challenge_not_configured:
      "Este formulario aún no está listo. Escribe a info@dustwave.xyz.",
    challenge_failed: "Falló la verificación. Inténtalo de nuevo.",
    challenge_unavailable:
      "La verificación no está disponible. Inténtalo de nuevo.",
    login_unavailable: "No pudimos enviar el enlace. Inténtalo de nuevo.",
    file_too_large: "Elige una imagen de menos de 5 MB.",
    invalid_image: "Elige una imagen JPEG, PNG o WebP.",
    notFound: "Esta página no está aquí.",
    notFoundBody:
      "El evento puede haberse quitado o la dirección puede ser incorrecta.",
    notice: "Avisos al público",
    readMore: "Leer más",
    removeImage: "Quitar imagen",
    uploading: "Preparando imagen…",
    privacy: "Privacidad",
    privacyText:
      "Solo el equipo del Microcine puede ver los datos de contacto que envías con tu propuesta. Los usamos para revisar tu idea y responderte. No te añadimos a una lista de correo. Para pedir que eliminemos tu propuesta, escribe a info@dustwave.xyz.",
    emptyArtwork: "IMAGEN DEL EVENTO",
    sessionLoad: "Comprobando tu sesión…",
    venueNote: "30 BUTACAS\nESTUDIO DUST WAVE",
  },
};
